#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Rename Watcher Plugin
Обработка команды /rename для переименования чата
"""

import csv
import logging
import os
import random
from pyrogram import Client, filters
from pyrogram.types import Message
from pyrogram.enums import MessageServiceType
from pyrogram.errors import ChatAdminRequired, ChatNotModified
from config import get_settings, now_in_app_timezone

logger = logging.getLogger(__name__)


def _write_rename_to_csv(new_title: str, actor_username: str, source_username: str):
    """Записать факт переименования в CSV-файл статистики"""
    try:
        settings = get_settings()
        data_dir = settings.get("session_path", "data")
        os.makedirs(data_dir, exist_ok=True)
        csv_file = os.path.join(data_dir, "chat_title_changes.csv")

        write_header = not os.path.exists(csv_file)
        timestamp = now_in_app_timezone().isoformat()

        with open(csv_file, "a", newline="", encoding="utf-8") as f:
            writer = csv.writer(f)
            if write_header:
                writer.writerow(["timestamp", "new_title", "changed_by_username", "title_source_username"])
            writer.writerow([timestamp, new_title, actor_username, source_username])

        logger.info(
            f"Rename logged: new_title='{new_title}', "
            f"actor=@{actor_username}, source=@{source_username}"
        )
    except Exception as e:
        logger.error(f"Failed to write rename to CSV: {str(e)}", exc_info=True)


async def handle_rename(client: Client, message: Message):
    """
    Обработка команды /rename

    Объединяет логику:
    - Извлечение нового названия из сообщения/ответа
    - Валидация и обрезка до 255 символов
    - Удаление командного сообщения
    - Вызов client.set_chat_title()
    - Запись статистики в CSV (кто переименовал + чьё сообщение стало названием)
    - Обработка ошибок
    """
    try:
        new_title = None
        source_username = None

        if message.reply_to_message:
            if message.reply_to_message.text:
                new_title = message.reply_to_message.text
                # Чьё сообщение использовано как новое название
                reply = message.reply_to_message
                if reply.from_user:
                    source_username = reply.from_user.username or reply.from_user.first_name or "user"
                elif reply.sender_chat:
                    source_username = reply.sender_chat.title or "chat"
                else:
                    source_username = "user"
            else:
                await message.delete()
                return
        elif message.text and len(message.text.split(maxsplit=1)) > 1:
            new_title = message.text.split(maxsplit=1)[1]
            source_username = None  # название задано напрямую, не из чужого сообщения
        else:
            await message.delete()
            return

        if not new_title or not new_title.strip():
            await message.delete()
            return

        if len(new_title) > 255:
            new_title = new_title[:255]

        await message.delete()

        chat_id = message.chat.id
        logger.info(
            f"Bot about to rename chat {chat_id} to: '{new_title}' - "
            f"This will generate a service message"
        )

        # set_chat_title generates a service message, but Pyrogram doesn't deliver
        # it back to the bot's handlers, so we need to find and delete it manually
        await client.set_chat_title(chat_id, new_title.strip())

        logger.info(
            f"Chat {chat_id} renamed to: {new_title} - "
            f"Service message should have been generated by Telegram, attempting to delete it"
        )

        # The service message is created after set_chat_title, we need to fetch
        # recent messages and delete the service message
        try:
            # Get the most recent message (should be the service message)
            async for msg in client.get_chat_history(chat_id, limit=1):
                if msg.service and msg.service == MessageServiceType.NEW_CHAT_TITLE:
                    await msg.delete()
                    logger.info(
                        f"Successfully deleted service message (id: {msg.id}) "
                        f"generated by bot's rename action"
                    )
                break
        except Exception as e:
            logger.error(
                f"Failed to delete service message after bot rename: {str(e)}",
                exc_info=True
            )

        # Определяем, кто вызвал /rename
        if message.from_user:
            actor_username = message.from_user.username or message.from_user.first_name or "user"
        elif message.sender_chat:
            actor_username = message.sender_chat.title or "chat"
        else:
            actor_username = "user"

        _write_rename_to_csv(new_title, actor_username, source_username or actor_username)

    except ChatAdminRequired:
        logger.error(f"Bot lacks admin rights in chat {message.chat.id}")
    except ChatNotModified:
        logger.info(
            f"Chat {message.chat.id} title not modified (already set to same value)"
        )
        await message.delete()
    except Exception as e:
        logger.error(f"Error in rename handler: {str(e)}", exc_info=True)


def register_handler(client: Client, group: int = 0):
    """Регистрация обработчика команды /rename"""

    @client.on_message(filters.command("rename") & filters.group, group=group)
    async def rename_wrapper(client: Client, message: Message):
        await handle_rename(client, message)
        await message.continue_propagation()

    @client.on_message(filters.command(["ренейм", "ренаме"]) & filters.group, group=group)
    async def rename_ru_wrapper(client: Client, message: Message):
        if random.random() > 0.1:
            await message.continue_propagation()
            return
        await handle_rename(client, message)
        await message.continue_propagation()

    logger.info("Rename watcher handler registered")
